; Sound Effects for song New song, version 2.0, generated by Arkos Tracker 2.

GoldorakSoundFX_SoundEffects
GoldorakSoundFX_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
GoldorakSoundFX_SoundEffectsDisarkPointerRegionStart0
	dw GoldorakSoundFX_SoundEffects_Sound1	; Sound effect 1.
	dw GoldorakSoundFX_SoundEffects_Sound2	; Sound effect 2.
	dw GoldorakSoundFX_SoundEffects_Sound3	; Sound effect 3.
	dw GoldorakSoundFX_SoundEffects_Sound4	; Sound effect 4.
	dw GoldorakSoundFX_SoundEffects_Sound5	; Sound effect 5.
	dw GoldorakSoundFX_SoundEffects_Sound6	; Sound effect 6.
	dw GoldorakSoundFX_SoundEffects_Sound7	; Sound effect 7.
	dw GoldorakSoundFX_SoundEffects_Sound8	; Sound effect 8.
	dw GoldorakSoundFX_SoundEffects_Sound9	; Sound effect 9.
	dw GoldorakSoundFX_SoundEffects_Sound10	; Sound effect 10.
	dw GoldorakSoundFX_SoundEffects_Sound11	; Sound effect 11.
	dw GoldorakSoundFX_SoundEffects_Sound12	; Sound effect 12.
GoldorakSoundFX_SoundEffectsDisarkPointerRegionEnd0

GoldorakSoundFX_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
GoldorakSoundFX_SoundEffects_Sound1
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound1_Loop	db 165	; Soft only. Volume: 9.
	db 14	; Noise: 14.
	dw 238	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 32	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 60	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 89	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 119	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 150	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 178	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 213	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 238	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 225	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 214	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 189	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 239	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 283	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 339	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 379	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 426	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 479	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 540	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 568	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 598	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 680	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
GoldorakSoundFX_SoundEffects_Sound2
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound2_Loop	db 61	; Soft only. Volume: 15.
	dw 170	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 222	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 247	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 146	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 170	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 222	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 247	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 146	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 170	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 222	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 247	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 306	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 334	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 371	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 419	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
GoldorakSoundFX_SoundEffects_Sound3
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound3_Loop	db 182	; Hard only. Env: 14. Retrig.
	db 12	; Noise: 12.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 10	; Noise: 10.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 8	; Noise: 8.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 6	; Noise: 6.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 4	; Noise: 4.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 2	; Noise: 2.
	dw 6	; Hardware period.

	db 54	; Hard only. Env: 14. Retrig.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 1	; Noise: 1.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 2	; Noise: 2.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 3	; Noise: 3.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 4	; Noise: 4.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 5	; Noise: 5.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 6	; Noise: 6.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 7	; Noise: 7.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 8	; Noise: 8.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 9	; Noise: 9.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 10	; Noise: 10.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 11	; Noise: 11.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 12	; Noise: 12.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 13	; Noise: 13.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 14	; Noise: 14.
	dw 6	; Hardware period.

	db 182	; Hard only. Env: 14. Retrig.
	db 15	; Noise: 15.
	dw 6	; Hardware period.

	db 4	; End of the sound effect.

; Sound effect 4.
GoldorakSoundFX_SoundEffects_Sound4
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound4_Loop	db 185	; Soft only. Volume: 14.
	db 31	; Noise: 31.
	dw 15	; Software period.

	db 185	; Soft only. Volume: 14.
	db 31	; Noise: 31.
	dw 15	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 16	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 16	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 18	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 18	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 18	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 18	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 19	; Software period.

	db 173	; Soft only. Volume: 11.
	db 31	; Noise: 31.
	dw 19	; Software period.

	db 173	; Soft only. Volume: 11.
	db 31	; Noise: 31.
	dw 20	; Software period.

	db 173	; Soft only. Volume: 11.
	db 31	; Noise: 31.
	dw 20	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 20	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 21	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 21	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 21	; Software period.

	db 165	; Soft only. Volume: 9.
	db 31	; Noise: 31.
	dw 22	; Software period.

	db 165	; Soft only. Volume: 9.
	db 31	; Noise: 31.
	dw 22	; Software period.

	db 165	; Soft only. Volume: 9.
	db 31	; Noise: 31.
	dw 22	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 24	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 24	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 24	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 25	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 25	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 27	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 27	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 27	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 28	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 28	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 28	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 30	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 30	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 30	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 30	; Software period.

	db 145	; Soft only. Volume: 4.
	db 31	; Noise: 31.
	dw 33	; Software period.

	db 145	; Soft only. Volume: 4.
	db 31	; Noise: 31.
	dw 33	; Software period.

	db 145	; Soft only. Volume: 4.
	db 31	; Noise: 31.
	dw 32	; Software period.

	db 141	; Soft only. Volume: 3.
	db 31	; Noise: 31.
	dw 32	; Software period.

	db 141	; Soft only. Volume: 3.
	db 31	; Noise: 31.
	dw 32	; Software period.

	db 141	; Soft only. Volume: 3.
	db 31	; Noise: 31.
	dw 34	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
GoldorakSoundFX_SoundEffects_Sound5
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound5_Loop	db 61	; Soft only. Volume: 15.
	dw 213	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 303	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 379	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 445	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 531	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 643	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 718	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 809	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 915	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 953	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 1088	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 1141	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 1201	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 1267	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 1338	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 1417	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 1504	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 1597	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 1700	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 1811	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 1930	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 1895	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 1895	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 1895	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 1895	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 1895	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 1895	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 1895	; Software period.

	db 4	; End of the sound effect.

; Sound effect 6.
GoldorakSoundFX_SoundEffects_Sound6
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound6_Loop	db 61	; Soft only. Volume: 15.
	dw 17	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 15	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 17	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 20	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 24	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 24	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 23	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 28	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 27	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 29	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 29	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 26	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 39	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 32	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 34	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 31	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 33	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 40	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 43	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 40	; Software period.

	db 4	; End of the sound effect.

; Sound effect 7.
GoldorakSoundFX_SoundEffects_Sound7
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound7_Loop	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 3804	; Hardware period.
	dw 32	; Software period.

	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 2533	; Hardware period.
	dw 46	; Software period.

	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 1893	; Hardware period.
	dw 62	; Software period.

	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 3804	; Hardware period.
	dw 32	; Software period.

	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 2533	; Hardware period.
	dw 46	; Software period.

	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 1893	; Hardware period.
	dw 62	; Software period.

	db 15	; Soft and Hard. Env: 9. Retrig.
	dw 3804	; Hardware period.
	dw 32	; Software period.

	db 4	; End of the sound effect.

; Sound effect 8.
GoldorakSoundFX_SoundEffects_Sound8
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound8_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 173	; Soft only. Volume: 11.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 173	; Soft only. Volume: 11.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 165	; Soft only. Volume: 9.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 165	; Soft only. Volume: 9.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 161	; Soft only. Volume: 8.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 161	; Soft only. Volume: 8.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 157	; Soft only. Volume: 7.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 157	; Soft only. Volume: 7.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 153	; Soft only. Volume: 6.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 153	; Soft only. Volume: 6.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 149	; Soft only. Volume: 5.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 149	; Soft only. Volume: 5.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 145	; Soft only. Volume: 4.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 145	; Soft only. Volume: 4.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 141	; Soft only. Volume: 3.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 141	; Soft only. Volume: 3.
	db 1	; Noise: 1.
	dw 815	; Software period.

	db 4	; End of the sound effect.

; Sound effect 9.
GoldorakSoundFX_SoundEffects_Sound9
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound9_Loop	db 248	; No soft, no hard. Volume: 15.
	db 30	; Noise: 30.

	db 240	; No soft, no hard. Volume: 14.
	db 30	; Noise: 30.

	db 240	; No soft, no hard. Volume: 14.
	db 30	; Noise: 30.

	db 232	; No soft, no hard. Volume: 13.
	db 30	; Noise: 30.

	db 232	; No soft, no hard. Volume: 13.
	db 30	; Noise: 30.

	db 232	; No soft, no hard. Volume: 13.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 224	; No soft, no hard. Volume: 12.
	db 30	; Noise: 30.

	db 216	; No soft, no hard. Volume: 11.
	db 30	; Noise: 30.

	db 216	; No soft, no hard. Volume: 11.
	db 30	; Noise: 30.

	db 208	; No soft, no hard. Volume: 10.
	db 30	; Noise: 30.

	db 208	; No soft, no hard. Volume: 10.
	db 30	; Noise: 30.

	db 208	; No soft, no hard. Volume: 10.
	db 30	; Noise: 30.

	db 200	; No soft, no hard. Volume: 9.
	db 30	; Noise: 30.

	db 200	; No soft, no hard. Volume: 9.
	db 30	; Noise: 30.

	db 192	; No soft, no hard. Volume: 8.
	db 30	; Noise: 30.

	db 192	; No soft, no hard. Volume: 8.
	db 30	; Noise: 30.

	db 192	; No soft, no hard. Volume: 8.
	db 30	; Noise: 30.

	db 184	; No soft, no hard. Volume: 7.
	db 30	; Noise: 30.

	db 184	; No soft, no hard. Volume: 7.
	db 30	; Noise: 30.

	db 176	; No soft, no hard. Volume: 6.
	db 30	; Noise: 30.

	db 176	; No soft, no hard. Volume: 6.
	db 30	; Noise: 30.

	db 176	; No soft, no hard. Volume: 6.
	db 30	; Noise: 30.

	db 168	; No soft, no hard. Volume: 5.
	db 30	; Noise: 30.

	db 168	; No soft, no hard. Volume: 5.
	db 30	; Noise: 30.

	db 160	; No soft, no hard. Volume: 4.
	db 30	; Noise: 30.

	db 160	; No soft, no hard. Volume: 4.
	db 30	; Noise: 30.

	db 160	; No soft, no hard. Volume: 4.
	db 30	; Noise: 30.

	db 4	; End of the sound effect.

; Sound effect 10.
GoldorakSoundFX_SoundEffects_Sound10
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound10_Loop	db 189	; Soft only. Volume: 15.
	db 14	; Noise: 14.
	dw 310	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 316	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 325	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 337	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 424	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 449	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 478	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 428	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 461	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 500	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 543	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 593	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 543	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 599	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 660	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 610	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 679	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 754	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 704	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 786	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 736	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 828	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 778	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 876	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 826	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 934	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 884	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 1002	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 952	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 902	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 1028	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 978	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 1117	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 1067	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1017	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1165	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1115	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1065	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1226	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1176	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1350	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1300	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1250	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1200	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1385	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1335	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1285	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 1487	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 1437	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 1387	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 1602	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 1552	; Software period.

	db 4	; End of the sound effect.

; Sound effect 11.
GoldorakSoundFX_SoundEffects_Sound11
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound11_Loop	db 189	; Soft only. Volume: 15.
	db 14	; Noise: 14.
	dw 54	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 44	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 37	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 32	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 82	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 86	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 94	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 44	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 54	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 69	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 87	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 109	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 59	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 86	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 117	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 67	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 103	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 144	; Software period.

	db 189	; Soft only. Volume: 15.
	db 15	; Noise: 15.
	dw 94	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 141	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 91	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 143	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 93	; Software period.

	db 185	; Soft only. Volume: 14.
	db 15	; Noise: 15.
	dw 152	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 102	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 166	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 116	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 188	; Software period.

	db 181	; Soft only. Volume: 13.
	db 15	; Noise: 15.
	dw 138	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 88	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 166	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 116	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 203	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 153	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 103	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 198	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 148	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 98	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 201	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 151	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 264	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 214	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 164	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 114	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 235	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 185	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 135	; Software period.

	db 173	; Soft only. Volume: 11.
	db 15	; Noise: 15.
	dw 268	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 218	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 168	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 310	; Software period.

	db 169	; Soft only. Volume: 10.
	db 15	; Noise: 15.
	dw 260	; Software period.

	db 4	; End of the sound effect.

; Sound effect 12.
GoldorakSoundFX_SoundEffects_Sound12
	db 0	; Speed

GoldorakSoundFX_SoundEffects_Sound12_Loop	db 13	; Soft only. Volume: 3.
	dw 45	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 47	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 50	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 53	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 60	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 63	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 71	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 75	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 80	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 89	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 95	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 106	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 113	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 127	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 134	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 142	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 159	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 169	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 179	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 190	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 213	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 225	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 253	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 268	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 284	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 319	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 338	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 358	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 379	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 426	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 451	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 506	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 536	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 568	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 602	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 676	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 716	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 804	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 851	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 902	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 1012	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 1073	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 1204	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 1276	; Software period.

	db 4	; End of the sound effect.

GoldorakSoundFX_SoundEffectsDisarkByteRegionEnd1
